const USER_CONSULTATIONS_API = ["DOCTOR"];
const DOCTOR_CONSULTATIONS_API = ["USER", "ADMIN"];

const ApiAuthRoles = {
    DOCTOR_CONSULTATIONS_API,
    USER_CONSULTATIONS_API
}

export default ApiAuthRoles;
